# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{ cron: "0 6 * * 1" }] # Every Monday at 6:00 am
  workflow_dispatch:
  push:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: METRICS_TOKEN
    permissions:
      contents: write
    steps:
      - name: 🦑 General
        uses: lowlighter/metrics@latest
        with:
          filename: assets/general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: luluw8071
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kathmandu

          # Discussions:
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_followup: yes
          # plugin_followup_indepth: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories

          # About Me:
          plugin_introduction: yes
          plugin_introduction_title: yes

          # Habits:
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

          # Language:
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: jupyter notebook
          plugin_languages_limit: 8
          # plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

      - name: 🦑 Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: assets/achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_fortune: yes
